export const REVIEW_CREATE_REQUEST          = 'REVIEW_CREATE_REQUEST';
export const REVIEW_CREATE_SUCCESS          = 'REVIEW_CREATE_SUCCESS';
export const REVIEW_CREATE_FAIL             = 'REVIEW_CREATE_FAIL';
export const REVIEW_CREATE_RESET            = 'REVIEW_CREATE_RESET';

export const REVIEW_DELETE_REQUEST          = 'REVIEW_DELETE_REQUEST';
export const REVIEW_DELETE_SUCCESS          = 'REVIEW_DELETE_SUCCESS';
export const REVIEW_DELETE_FAIL             = 'REVIEW_DELETE_FAIL';
export const REVIEW_DELETE_RESET            = 'REVIEW_DELETE_RESET';

export const REVIEW_PRODUCT_LIST_REQUEST    = 'REVIEW_PRODUCT_LIST_REQUEST';
export const REVIEW_PRODUCT_LIST_SUCCESS    = 'REVIEW_PRODUCT_LIST_SUCCESS';
export const REVIEW_PRODUCT_LIST_FAIL       = 'REVIEW_PRODUCT_LIST_FAIL';
export const REVIEW_PRODUCT_LIST_RESET      = 'REVIEW_PRODUCT_LIST_RESET';

export const REVIEW_UPDATE_REQUEST          = 'REVIEW_UPDATE_REQUEST'
export const REVIEW_UPDATE_SUCCESS          = 'REVIEW_UPDATE_SUCCESS'
export const REVIEW_UPDATE_FAIL             = 'REVIEW_UPDATE_FAIL'
export const REVIEW_UPDATE_RESET            = 'REVIEW_UPDATE_RESET'

export const REVIEW_MINE_LIST_REQUEST       = 'REVIEW_MINE_LIST_REQUEST';
export const REVIEW_MINE_LIST_SUCCESS       = 'REVIEW_MINE_LIST_SUCCESS';
export const REVIEW_MINE_LIST_FAIL          = 'REVIEW_MINE_LIST_FAIL';

export const REVIEW_USER_LIST_REQUEST       = 'REVIEW_USER_LIST_REQUEST';
export const REVIEW_USER_LIST_SUCCESS       = 'REVIEW_USER_LIST_SUCCESS';
export const REVIEW_USER_LIST_FAIL          = 'REVIEW_USER_LIST_FAIL';
export const REVIEW_USER_LIST_RESET         = 'REVIEW_USER_LIST_RESET';
